version: '3.3'

services:
  # cms:
  #   build: .
  #   image: cms
  #   container_name: hcms__api 
  #   env_file:
  #     - ./src/config/.env
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./logs:/app/logs
  db:
    image: mongo:latest
    container_name: hcms__db
    restart: always
    env_file:
      - ./src/config/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 8001:27017
    # volumes:
    #   - ./db_data:/data/db:Z

volumes:
  logs:
  # db_data:
  #   driver: local